
#DNA-mRNA Game
import time

def website1():
    print('Welcome to the DNA to mRNA conversion')

    print('All the letters have to be either A,T,C,G in pairs of three')
    

    print('MAKE SURE ALL OF YOUR LETTERS ARE CAPITAL WHEN TYPING THEM IN')
        
    game = input('Type in the three letters you want to convert to mRNA')

    game1 = 'AAA'
    game2 = 'AAG'
    game3 = 'AAT'
    game4 = 'AAC'
    game5 = 'AGA'
    game6 = 'AGG'
    game7 = 'AGT'
    game8 = 'AGC'
    game9 = 'ATA'
    game10 = 'ATG'
    game11 = 'ATT'
    game12 = 'ATC' 
    game13 = 'ACA'
    game14 = 'ACG'
    game15 = 'ACT'
    game16 = 'ACC'
    game17 = 'GAA'
    game18 = 'GAG'
    game19 = 'GAT'
    game20 = 'GAC'
    game21 = 'GGA'
    game22 = 'GGG'
    game23 = 'GGT'
    game24 = 'GGC'
    game25 = 'GTA'
    game26 = 'GTG'
    game27 = 'GTT'
    game28 = 'GTC'
    game29 = 'GCA'
    game30 = 'GCG'
    game31 = 'GCT'
    game32 = 'GCC'
    game33 = 'TAA'
    game34 = 'TAG'
    game35 = 'TAT'
    game36 = 'TAC'
    game37 = 'TGA'
    game38 = 'TGG'
    game39 = 'TGT'
    game40 = 'TGC'
    game41 = 'TTA'
    game42 = 'TTG' 
    game43 = 'TTT'
    game44 = 'TTC'
    game45 = 'TCA'
    game46 = 'TCG'
    game47 = 'TCT'
    game48 = 'TCC'
    game49 = 'CAA'
    game50 = 'CAG'
    game51 = 'CAT'
    game52 = 'CAC'
    game53 = 'CGA'
    game54 = 'CGG'
    game55 = 'CGT'
    game56 = 'CGC'
    game57 = 'CTA'
    game58 = 'CTG'
    game59 = 'CTT'
    game60 = 'CTC'
    game61 = 'CCA'
    game62 = 'CCG'
    game63 = 'CCT'
    game64 = 'CCC'


    if game == game1:
        print('This converts to - UUU')

    if game == game2:
        print('This converts to - UUC')

    if game == game3:
        print('This converts to - UUA')

    if game == game4:
        print('This converts to - UUG')

    if game == game5:
        print('This converts to - UCU')

    if game == game6:
        print('This converts to - UCC')

    if game == game7:
        print('This converts to - UCA')

    if game == game8:
        print('This converts to - UCG')

    if game == game9:
        print('This converts to - UAU')

    if game == game10:
        print('This converts to - UAC')

    if game == game11:
        print('This converts to - UAA')

    if game == game12:
        print('This converts to - UAG')

    if game == game13:
        print('This converts to - UGU')

    if game == game14:
        print('This converts to - UGC')

    if game == game15:
        print('This converts to - UGA')

    if game == game16:
        print('This converts to - UGG')

    if game == game17:
        print('This converts to - CUU')

    if game == game18:
        print('This converts to - CUC')

    if game == game19:
        print('This converts to - CUA')

    if game == game20:
        print('This converts to - CUG')

    if game == game21:
        print('This converts to - CCU')

    if game == game22:
        print('This converts to - CCC')

    if game == game23:
        print('This converts to - CCA')

    if game == game24:
        print('This converts to - CCG')

    if game == game25:
        print('This converts to - CAU')

    if game == game26:
        print('This converts to - CAC')

    if game == game27:
        print('This converts to - CAA')

    if game == game28:
        print('This converts to - CAG')

    if game == game29:
        print('This converts to - CGU')

    if game == game30:
        print('This converts to - CGC')

    if game == game31:
        print('This converts to - CGA')

    if game == game32:
        print('This converts to - CGG')

    if game == game33:
        print('This converts to - AUU')

    if game == game34:
        print('This converts to - AUC')

    if game == game35:
        print('This converts to - AUA')

    if game == game36:
        print('This converts to - AUG')

    if game == game37:
        print('This converts to - ACU')

    if game == game38:
        print('This converts to - ACC')

    if game == game39:
        print('This converts to - ACA')

    if game == game40:
        print('This converts to - ACG')

    if game == game41:
        print('This converts to - AAU')

    if game == game42:
        print('This converts to - AAC')

    if game == game43:
        print('This converts to - AAA')

    if game == game44:
        print('This converts to - AAG')

    if game == game45:
        print('This converts to - AGU')

    if game == game46:
        print('This converts to - AGC')

    if game == game47:
        print('This converts to - AGA')

    if game == game48:
        print('This converts to - AGG')

    if game == game49:
        print('This converts to - GUU')

    if game == game50:
        print('This converts to - GUC')

    if game == game51:
        print('This converts to - GUA')

    if game == game52:
        print('This converts to - GUG')

    if game == game53:
        print('This converts to - GCU')

    if game == game54:
        print('This converts to - GCC')

    if game == game55:
        print('This converts to - GCA')

    if game == game56:
        print('This converts to - GCG')

    if game == game57:
        print('This converts to - GAU')

    if game == game58:
        print('This converts to - GAC')

    if game == game59:
        print('This converts to - GAA')

    if game == game60:
        print('This converts to - GAG')

    if game == game61:
        print('This converts to - GGU')

    if game == game62:
        print('This converts to - GGC')

    if game == game63:
        print('This converts to - GGA')

    if game == game64:
        print('This converts to - GGG')


    fifteen = input('Do you want to exit this code and start again to start new, Y/N')

    if fifteen == 'y':
        exit()

    time.sleep(2)

def website():
    print('Welcome to the mRNA to Protein converter')

    print('All the letters have to be either U, A, C, G in pairs of three')
        
    print('MAKE SURE ALL OF YOUR LETTERS ARE CAPITAL WHEN TYPING THEM IN')

    game = input('Type in the three letters you want to convert to proteins')

    game1 = 'UUU'
    game2 = 'UUC'
    game3 = 'UUA'
    game4 = 'UUG'
    game5 = 'UCU'
    game6 = 'UCC'
    game7 = 'UCA'
    game8 = 'UCG'
    game9 = 'UAU'
    game10 = 'UAC'
    game11 = 'UAA' 
    game12 = 'UAG'
    game13 = 'UGU'
    game14 = 'UGC'
    game15 = 'UGA'
    game16 = 'UGG'
    game17 = 'CUU'
    game18 = 'CUC'
    game19 = 'CUA'
    game20 = 'CUG'
    game21 = 'CCU'
    game22 = 'CCC'
    game23 = 'CCA'
    game24 = 'CCG'
    game25 = 'CAU'
    game26 = 'CAC'
    game27 = 'CAA'
    game28 = 'CAG'
    game29 = 'CGU'
    game30 = 'CGC'
    game31 = 'CGA'
    game32 = 'CGG'
    game33 = 'AUU'
    game34 = 'AUC'
    game35 = 'AUA'
    game36 = 'AUG'
    game37 = 'ACU'
    game38 = 'ACC'
    game39 = 'ACA'
    game40 = 'ACG'
    game41 = 'AAU' 
    game42 = 'AAC'
    game43 = 'AAA'
    game44 = 'AAG'
    game45 = 'AGU'
    game46 = 'AGC'
    game47 = 'AGA'
    game48 = 'AGG'
    game49 = 'GUU'
    game50 = 'GUC'
    game51 = 'GUA'
    game52 = 'GUG'
    game53 = 'GCU'
    game54 = 'GCC'
    game55 = 'GCA'
    game56 = 'GCG'
    game57 = 'GAU'
    game58 = 'GAC'
    game59 = 'GAA'
    game60 = 'GAG'
    game61 = 'GGU'
    game62 = 'GGC'
    game63 = 'GGA'
    game64 = 'GGG'

    if game == game1:
        print('This converts to - phenylalanine')

    if game == game2:
        print('This converts to - phenylalanine')

    if game == game3:
        print('This converts to - leucine')

    if game == game4:
        print('This converts to - leucine')

    if game == game5:
        print('This converts to - serine')

    if game == game6:
        print('This converts to - serine')

    if game == game7:
        print('This converts to - serine')

    if game == game8:
        print('This converts to - serine')

    if game == game9:
        print('This converts to - tyrosine')

    if game == game10:
        print('This converts to - tyrosine')

    if game == game11:
        print('This converts to - STOP')

    if game == game12:
        print('This converts to - STOP')

    if game == game13:
        print('This converts to - cysteine')

    if game == game14:
        print('This converts to - cysteine')

    if game == game15:
        print('This converts to - STOP')

    if game == game16:
        print('This converts to - tryptophan')

    if game == game17:
        print('This converts to - leucine')

    if game == game18:
        print('This converts to - leucine')

    if game == game19:
        print('This converts to - leucine')

    if game == game20:
        print('This converts to - leucine')

    if game == game21:
        print('This converts to - proline')

    if game == game22:
        print('This converts to - proline')

    if game == game23:
        print('This converts to - proline')

    if game == game24:
        print('This converts to - proline')

    if game == game25:
        print('This converts to - histidine')

    if game == game26:
        print('This converts to - histidine')

    if game == game27:
        print('This converts to - glutamine')

    if game == game28:
        print('This converts to - glutamine')

    if game == game29:
        print('This converts to - arginine')

    if game == game30:
        print('This converts to - arginine')

    if game == game31:
        print('This converts to - arginine')

    if game == game32:
        print('This converts to - arginine')

    if game == game33:
        print('This converts to - isoleucine')

    if game == game34:
        print('This converts to - isoleucine')

    if game == game35:
        print('This converts to - isoleucine')

    if game == game36:
        print('This converts to - methionine/START')

    if game == game37:
        print('This converts to - threonine')

    if game == game38:
        print('This converts to - threonine')

    if game == game39:
        print('This converts to - threonine')

    if game == game40:
        print('This converts to - threonine')

    if game == game41:
        print('This converts to - asparagine')

    if game == game42:
        print('This converts to - asparagine')

    if game == game43:
        print('This converts to - lysine')

    if game == game44:
        print('This converts to - lysine')

    if game == game45:
        print('This converts to - serine')

    if game == game46:
        print('This converts to - serine')

    if game == game47:
        print('This converts to - arginine')

    if game == game48:
        print('This converts to - arginine')

    if game == game49:
        print('This converts to - valine')

    if game == game50:
        print('This converts to - valine')

    if game == game51:
        print('This converts to - valine')

    if game == game52:
        print('This converts to - valine')

    if game == game53:
        print('This converts to - alanine')

    if game == game54:
        print('This converts to - alanine')

    if game == game55:
        print('This converts to - alanine')

    if game == game56:
        print('This converts to - alanine')

    if game == game57:
        print('This converts to - aspartate')

    if game == game58:
        print('This converts to - aspartate')

    if game == game59:
        print('This converts to - glutamate')

    if game == game60:
        print('This converts to - glutamate')

    if game == game61:
        print('This converts to - glycine')

    if game == game62:
        print('This converts to - glycine')

    if game == game63:
        print('This converts to - glycine')

    if game == game64:
        print('This converts to - glycine')


    fifteen = input('Do you want to exit this code and start again to start new, Y/N')

    if fifteen == 'y':
        exit()

    time.sleep(2)


turtle1 = input('Do you want to convert DNA to mRNA, learn about DNA and mRNA or convert proteins / press 1 to convert, press 2 to learn, press 3 to convert to proteins ')

if turtle1 == '2':
    print('''Hello this is the info center about DNA, mRNA and proteins. This part of the code will be changing over the course of the year as I learn
more new things about DNA and mRNA. DNA stands for Deoxyribonucleic acid, mRNA stands for Messenger ribonucleic acid. There are also proteins made after
DNA is converted to mRNA, these proteins are called by the name tRNA which stands for transfer ribonucleic acid.''')

if turtle1 == '3':
    while True:
        website()

if turtle1 == '1':
    while True:
        website1()


game = input("Do You want to convert DNA to mRNA, Type the password that allows you to go in")

correct = "password"

if game == correct:
    while True:
        website1()

if game != correct:
    print ("Sorry you are not allowed to enter the game, Try Again") 
